"""Module to retreive/declare the environment variables."""


import os

MAX_NOTIFICATION_RESULTS_COUNT = os.environ["MAX_NOTIFICATION_RESULTS_COUNT"]

LIBRARY_CATALOGUE_SITE_API = os.environ["LIBRARY_CATALOGUE_SITE_API"]
LIBRARY_CATALOGUE_SITE_URL = os.environ["LIBRARY_CATALOGUE_SITE_URL"]
LIBRARY_CATALOGUE_BACKOFFICE_ITEMS_API = os.environ[
    "LIBRARY_CATALOGUE_BACKOFFICE_ITEMS_API"
]
LIBRARY_CATALOGUE_BACKOFFICE_EITEMS_API = os.environ[
    "LIBRARY_CATALOGUE_BACKOFFICE_EITEMS_API"
]
LIBRARY_CATALOGUE_BACKOFFICE_API_TOKEN = os.environ[
    "LIBRARY_CATALOGUE_BACKOFFICE_API_TOKEN"
]

NOTIFICATIONS_API_URL = os.environ["NOTIFICATIONS_API_URL"]
NOTIFICATIONS_API_SECRET = os.environ["NOTIFICATIONS_API_SECRET"]
NOTIFICATIONS_CHANNEL_ID = os.environ["NOTIFICATIONS_CHANNEL_ID"]
