"""Module to retreive/declare the environment variables."""


import os

LIBRARY_CATALOGUE_SITE_API = os.environ.get("LIBRARY_CATALOUGE_SERVER", "")
LIBRARY_CATALOGUE_SITE_URL = os.environ.get("LIBRARY_CATALOGUE_SITE_URL", "")
LIBRARY_CATALOGUE_BACKOFFICE_API = os.environ.get(
    "LIBRARY_CATALOGUE_BACKOFFICE_URL", ""
)

NOTIFICATIONS_API_URL = os.environ.get("NOTIFICATIONS_API_URL", "")
NOTIFICATIONS_API_SECRET = os.environ.get("NOTIFICATIONS_API_SECRET", "")
NOTIFICATIONS_CHANNEL_ID = os.environ.get("NOTIFICATIONS_CHANNEL_ID", "")
